# Generated by Django 5.2.7 on 2025-10-04 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RewardItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_item', models.CharField(max_length=100)),
                ('reward_category_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_items', to='Rewards.rewardcategory')),
            ],
        ),
    ]
