# Generated by Django 5.2.7 on 2025-10-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chest',
            name='chest',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='reward_category',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rewarditems',
            name='reward_item',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
