# Generated by Django 5.2.7 on 2025-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0002_alter_chest_chest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditems',
            name='extra_notes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
