# Generated by Django 5.2.7 on 2025-10-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0003_rewarditems_extra_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewarditems',
            name='extra_notes',
        ),
    ]
