# Generated by Django 5.2.7 on 2025-10-04 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0004_remove_rewarditems_extra_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('extra_note', models.CharField(max_length=200)),
                ('chest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewards.chest')),
                ('reward_category_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewardcategory')),
                ('reward_items_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewarditems')),
            ],
        ),
    ]
