# Generated by Django 5.2.7 on 2025-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0005_chestrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestrecords',
            name='extra_note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
