# Generated by Django 5.2.7 on 2025-10-04 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rewards', '0006_alter_chestrecords_extra_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chestrecords',
            name='reward_category_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewardcategory'),
        ),
        migrations.AlterField(
            model_name='chestrecords',
            name='reward_items_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Rewards.rewarditems'),
        ),
    ]
